### PR TITLE
feat: 🎸 Add keyboard layout detection & format install script

### PR DESCRIPTION
**Pull request by kamack38**

### CODE REVIEW

**Comment by ldrahnik** [comment]
@kamack38 Can you push this part as well please?

```
And then is required to add code even to `asus_touchpad.py` because the layout can be changed during using numpad easily:

setxkbmap fr # -> to azerty

So in asus_touchpad.py:

join all threads to only one background running thread with 0.5s interval
add to endless loop function with the same code as to install.sh and with result set up variable percentage_key
```

**Comment by kamack38** [comment]
I'm not as good as you with python. Could you please commit that?

**Comment by ldrahnik** [comment]
Your first commit I `cherry-pick` ed to master.

I added a few lines of code according to your code added to `install.sh`, but, unfortunately, I face the same problem as in the other branch. Run these commands  (`xinput` or `setxkbmap`) requires GUI. At first, do not know why (these information should be possible get without display, maybe historical reason and association between code of libs like xorg display server etc.) but what is more important do not know if is possible to run these commands through `systemctl` service.

**Comment by kamack38** [comment]
> Your first commit I `cherry-pick` ed to master.
> 
> I added to `asus_touchad.py` a few lines of code according to your code added to `install.sh`, but, unfortunately, I face the same problem as in the other branch. Run these commands (`xinput` or `setxkbmap`) requires GUI. At first, do not know why (these information should be possible get without display, maybe historical reason and association between code of libs like xorg display server etc.) so what is more important do not know if is possible to run these commands through `systemctl` service.

That's probably because they're a xorg's commands.

**Comment by ldrahnik** [comment]
Well, looks like I fixed that. But what I explored as a subtask of this issue is the percents key because [does not exist direct key event for percents](https://github.com/whot/libevdev/blob/master/include/linux/input-event-codes.h). Maybe use something like mentioned [here](https://stackoverflow.com/questions/28362965/percent-sign-in-bash-is-not-typeable):


and then we could remove your code added in this branch (sorry, mine too) as only one reason why we need qwerty/azerty info at this moment is because of percents key, and exist a lot of layouts not only qwerty or azerty (for example my native czech use qwertz) and does not make sense hardcode them in driver AND!! key for percent can be rebound as well so clear solution might be something like mentioned in that post:

```
xmodmap -pke | grep percent
```

**Comment by ldrahnik** [comment]
Can you please test a master branch? If functionality disabling touchpad disable numpad now works for you?

**Comment by kamack38** [comment]
> Can you please test a master branch? If functionality disabling touchpad disable numpad now works for you?

Yes it works

**Comment by ldrahnik** [comment]
@kamack38 Ready for review (offline detection of numpad layout via file and automatic detection of key for percents). Offline table has to be filled with layouts. Online variant if is even possible I will commit separately.

**Comment by kamack38** [comment]
The install script doesn't seem to be working for me. There's a problem with automatic detection of a numpad layout.

**Comment by ldrahnik** [comment]
Hm, works for me. Can you post command which does not work for you / your distro?

**Comment by kamack38** [comment]
For detection, I think it would be a better idea to create a JSON object where each key would correspond to laptop name and the value would be a layout file. 
Something like this:
layouts.json
```json
{
    "G533QM-HF024T": "g533",
    "G533QM-HF093T": "g533",
    "G533QR-HF009T": "g533",
    "G533QS-HF007T": "g533",
    "G533QS-HF028T": "g533",
    "G533QS-HF186T": "g533",
    "G533ZW-LN123W": "g533",
    "G533ZX-LN004W": "g533",
    "G533ZX-LN064W": "g533"
}
```

**Comment by kamack38** [comment]
But this of course would require a JSON parser like `jq`, which size is `0,67 MiB`.

**Comment by kamack38** [comment]
@ldrahnik What do you think about the idea above?

**Comment by kamack38** [comment]
I think `python` has some JSON parsers pre-installed so installing `jq` would be unnecessary.

**Comment by ldrahnik** [comment]
I know `jq` and I like `jq` but in this case I think it is not a better option. Why? Speed, because I think is fastest cat and grep and benefits like nested structures and readability do not apply here. But maybe a delimiter could be a equal character:

```
UP5401EA-OLED123W=up5401ea
```

**Comment by kamack38** [comment]
I agree with you. JSON was just a spontaneous idea. I think that in this case (as you suggest) key=value storage would be a better idea.

**Comment by ldrahnik** [comment]
Can you try added commands directly in terminal from install.sh script? I would like figure out why it does not work for you.

**Comment by kamack38** [comment]
First of all it get's wrong layout name it's splits using `=` instead of `-`, then it get's the second (`HF007T`) part instead of the first (`G533QS`) one.  And in the end even if it would pick the correct thing (`G533QS`) it still is in caps and the file doesn't have the qs part, because the layout is for all laptops not only the QSs.

**Comment by kamack38** [comment]
So I would like to stick with the `key=value` storage, because it adds an option to reuse already existing layouts.

**Comment by kamack38** [comment]
I'm going to commit that in an hour.

**Comment by kamack38** [comment]
Now layout is detected automatically if no layout is given.

**Comment by kamack38** [comment]
I also added missing dependency (xinput). Because it may not be installed.

**Comment by ldrahnik** [comment]
What is your output `dmidecode -s system-product-name`?

**Comment by kamack38** [comment]
ROG STRIX G533QS_G533QS

**Comment by kamack38** [comment]
Why percentage key is layout dependent?

**Comment by ldrahnik** [comment]
Because percents key has no direct event key and has to be pressed with left shift key. Maybe exist a combination like alt+ number or something else but i am not sure it works across layouts. Feel free to look at that.

**Comment by ldrahnik** [comment]
Look at that now. Should be ready for a merge.

Code would be duplicated I kept an install script code.

**Comment by kamack38** [comment]
When I replaced one of the keys in the NoT with the `"EV...."` key and the I changed the layout to French azerty it printed the `"` character instead of %

**Comment by ldrahnik** [comment]
Weird, you're right. Looking at that.

**Comment by ldrahnik** [comment]
Yeah, because standardized version has no percent key with left shift binded :(

Second column after `=` is place for shift as special key: 
```
keycode  14 = parenleft 5 5 percent bracketleft dead_doubleacute
keycode  33 = p P p P percent permille
```

So has to be added support for other variant of special key. It should works.

**Comment by ldrahnik** [comment]
Looks like it not binded by default to any special key. What. Can you confirm that? I installed AFNOR Fr Standardized Azerty.

**Comment by ldrahnik** [comment]
But on `Default` Fr keyboard it works. I tested it with that. Its apostrophe key with left shift.

**Comment by kamack38** [comment]
The installation script doesn't work.

**Comment by kamack38** [comment]
I fixed it.

**Comment by kamack38** [comment]
I think that the better way (if we want to merge it with kernel) is to add the layout detection into the python program itself.

**Comment by ldrahnik** [comment]
Hm, I little prototyped with alt+values. A code:

```
        events = [
            InputEvent(EV_KEY.KEY_LEFTALT, 1),
            InputEvent(EV_SYN.SYN_REPORT, 0),
            InputEvent(EV_KEY.KEY_LEFTSHIFT, 1),
            InputEvent(EV_SYN.SYN_REPORT, 0),
            InputEvent(EV_KEY.KEY_U, 1),
            InputEvent(EV_SYN.SYN_REPORT, 0),
            InputEvent(EV_KEY.KEY_U, 0),
            InputEvent(EV_SYN.SYN_REPORT, 0),
        ]

        string = '%'

        for c in string:
            for hex_digit in '%X' % ord(c):

                key_code = getattr(ecodess, 'KEY_%s' % hex_digit)
                key = EV_KEY.codes[int(key_code)]
                events = events + [
                    InputEvent(key, 1),
                    InputEvent(EV_SYN.SYN_REPORT, 0),
                    InputEvent(key, 0),
                    InputEvent(EV_SYN.SYN_REPORT, 0)
                ]

            events = events + [
                InputEvent(EV_KEY.KEY_LEFTSHIFT, 0),
                InputEvent(EV_SYN.SYN_REPORT, 0),
                InputEvent(EV_KEY.KEY_LEFTALT, 0),
                InputEvent(EV_SYN.SYN_REPORT, 0)
            ]

            udev.send_events(events)

        return
```

and result is for `%` `U@%`, `U` because I have probably keybinding `leftalt+leftshift+u` = `U` and @ because `leftalt+leftshift+2` = `@` and then finally `leftshift+leftalt+U+25`=`%`.

**Comment by ldrahnik** [comment]
Has to be anyway rewritten to C language.

**Comment by ldrahnik** [comment]
So ways out of this: 1. Add note that who has percent on numpad is required have key binding with left shift (optionally add support for other special keys) 2. Figure out if I do not do something wrong when I use left shift +leftalt+U as it should be ekvivalent for windows alt+number.

**Comment by ldrahnik** [comment]
Should be fixed. Can you test it please. Works even on that french standardized keyboard. I was wrong, on linux it is not a alt but ctrl. So I reimplemented that as unicode sending, now is no needs have thread what is great also.

**Comment by kamack38** [comment]
> Should be fixed. Can you test it please. Works even on that french standardized keyboard. I was wrong, on linux it is not a left shift and left alt but left shift and left ctrl. So I reimplemented that as unicode sending, now is no needs have thread what is great also.

I've tested the newest commit on multiple keyboard layouts and everything seems to be working

**Pull request merged**
