### PR TITLE
#23 Drive connected to system numlock

### PR DESCRIPTION
**Pull request by ldrahnik**
Other `numlock` for desynchronization can be simulated for example with `numlockx`:

```
numlockx on
numlockx off
```

### CODE REVIEW

**Comment by ldrahnik** [comment]
@kamack38 Should work. The interval of reading system numlock state is atm hard coded, 0.5s.

**Comment by kamack38** [comment]
Unfortunately, this doesn't seem to be working for me. After clicking the *top right icon*, the *Numpad on Touchpad* activates for a half a second and then deactivates, but the numlock is still tuned on. Even if I press the numlock button (by executing `xdotool key Num_Lock`) the *NoT* does not activate.

**Comment by ldrahnik** [comment]
Even if I press the num lock button (by executing xdotool key Num_Lock) the NoT does not activate. 
> This is expected behaviour, when you use external keyboard laptop is put aside so enabling NoT when is used external keyboard numlock is unwanted.

But first part is not ok. NoT should be deactivated because then is not possible send keys via numpad. Can you please try run code in Visual Studio Code and put breakpoint on this row `leds_k = dev_k.leds(verbose=True)`. Run `xdotool key Num_Lock` (works for my laptop too) and check variable `leds_k`.

**Comment by kamack38** [comment]
I tried before, and I have `evdev` installed. But I will try using the VS Code breakpoint.

**Comment by ldrahnik** [comment]
When is system numlock on you should see:

image

**Comment by ldrahnik** [comment]
No, until now. Now I tested that with keyboard and it works as expected. External keyboard changes system numlock status and status is read via `evdev`.

**Comment by ldrahnik** [comment]
Weird. What you described happened to me now. But only once. Then every attempt to break was unsuccessful

**Comment by kamack38** [comment]
Also, I don't know why, but I don't get any debug messages. I'm running:
```bash
LOG=DEBUG sudo ./asus_touchpad.py g533 6
```

**Comment by ldrahnik** [comment]
> ..on, the Numpad on Touchpad activates for a half a second and then deactivates..

Did you stop installed service ```sudo systemctl stop asus_touchpad_numpad.service``` when you were debugging in Visual Studio?

**Comment by kamack38** [comment]
Yes, I did.

**Comment by kamack38** [comment]
Also, I got this exception while pressing the NumLock during debug. But I think this happened, because of the debug mode.
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kamack38/.vscode/extensions/ms-python.python-2022.10.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/kamack38/.vscode/extensions/ms-python.python-2022.10.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/kamack38/.vscode/extensions/ms-python.python-2022.10.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/kamack38/.vscode/extensions/ms-python.python-2022.10.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/kamack38/.vscode/extensions/ms-python.python-2022.10.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/kamack38/.vscode/extensions/ms-python.python-2022.10.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/kamack38/Documents/GitHUB/asus-touchpad-numpad-driver/asus_touchpad.py", line 605, in <module>
    listen_touchpad_events()
  File "/home/kamack38/Documents/GitHUB/asus-touchpad-numpad-driver/asus_touchpad.py", line 493, in listen_touchpad_events
    for e in d_t.events():
  File "/usr/lib/python3.10/site-packages/libevdev/device.py", line 541, in events
    raise EventsDroppedException()
libevdev.device.EventsDroppedException
```

**Comment by ldrahnik** [comment]
Ok. Yes, when you use during debugging breakpoints, it will break the code and you have to start debugging again.

**Comment by kamack38** [comment]
Currently, I have only Garuda Linux Lite on a pen drive, which is built on Arch. Can I use it?

**Comment by ldrahnik** [comment]
Yeah, atm I have no clue why it does work

**Comment by kamack38** [comment]
Okay, I tried on a live USB and a result is the same.

**Comment by ldrahnik** [comment]
Should be a possible list of all controllable LEDs by checking the content of the virtual directory ```/sys/class/leds/```

In my case input is `input34`:

```
$ cat /sys/class/leds/input34\:\:numlock/brightness 0
$ numlockx on
$ cat /sys/class/leds/input34\:\:numlock/brightness 1
```

It works? Is brightness changed?

**Comment by kamack38** [comment]
Here's my output
```bash
$ cat /sys/class/leds/input16::numlock/brightness
0
$ cat /sys/class/leds/input36::numlock/brightness
0
$ xdotool key Num_Lock
$ cat /sys/class/leds/input16::numlock/brightness
1
$ cat /sys/class/leds/input36::numlock/brightness
1
```
It showed me two devices that had the numlock led.

**Comment by kamack38** [comment]
Have you tried using this script with external keyboard?

**Comment by ldrahnik** [comment]
Yeah, 2 days ago and it works as expected. Nothing changed yet, I mean in principle. I just did a rebase to master branch and minor changes, nothing to do with `evdev`. I believe this solution should work across distributions.

Because from this file should `evdev` python lib (which server as interface over devices) read values. In this input virtual directory should exist dir `device` to correspond device under is `input` registered. Do please `cd /sys/class/leds/input16/device` and you should see the directory `eventX` directory. Is this `X` number the same when you put the breakpoint for variable `keyboard` in driver code? And `cat /sys/class/leds/input16/device/name` should be `AT Translated Set 2 keyboard` or with Asus Keyboard in the name.

Previous served for check in code is detected correct keyboard.
Now second check of connection between this file and evdev. Can you change import to:

Add on row `570`:

```
result = dev_k.capabilities(verbose=True)
```

and print output here. The result should be these input folders, in my case keyboard is `'AT Translated Set 2 keyboard'` and has these inputs:
```
$ ls -la
...
drwxr-xr-x 3 root root    0 Jul 10 09:09 input3::capslock
drwxr-xr-x 3 root root    0 Jul 10 09:09 input3::numlock
drwxr-xr-x 3 root root    0 Jul 10 09:09 input3::scrolllock
...
```

and my output of capabilities is:

```
...
('EV_LED', 17):
[('LED_NUML', 0), ('LED_CAPSL', 1), ('LED_SCROLLL', 2)]
```

Also, as is visible on listing inputs, root has to have access to read these files. 

And if it still does not work, try atleast setting leds values via adding import:

```from evdev import InputDevice, ecodes```

so includes now `ecodes` and on row `570`:

```dev_k.set_led(ecodes.LED_NUML, 1)```

put breakpoint below, in terminal check file `brigthness` if is set from `0` to  `1`.

**Comment by ldrahnik** [comment]
Check also capabilities for found `touchpad` with these lines entered on the bottom for example:

```
# touchpad capatibilities
fd_t = open('/dev/input/event' + str(touchpad), 'rb')
d_t = Device(fd_t)
result = dev_k.capabilities(verbose=True)
```

I see the same:

```
...
('EV_LED', 17):
[('LED_NUML', 0), ('LED_CAPSL', 1), ('LED_SCROLLL', 2)]
```

**Comment by kamack38** [comment]
bash: cd: /sys/class/leds/input16/device: No such file or directory

**Comment by kamack38** [comment]
```
cat: /sys/class/leds/input16/device/name: No such file or directory
```

**Comment by ldrahnik** [comment]
So let's try it from the other side.

Find event numbers via `xinput` and `xinput --list props <specific number from xinput list>` or run code and look at variables `touchpad` and `keyboard`.

Then do:

```cd /sys/class/input/event3/device``` and check if exist there exist dirs with inputs like I have:

```
...
drwxr-xr-x 3 root root    0 Jul 10 09:09 input3::capslock
drwxr-xr-x 3 root root    0 Jul 10 09:09 input3::numlock
drwxr-xr-x 3 root root    0 Jul 10 09:09 input3::scrolllock
...
```

**Comment by kamack38** [comment]
```
$ /sys/class/leds
lrwxrwxrwx 0 root 10 lip 15:42 asus-wireless::airplane -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/ATK4002:00/leds/asus-wireless::airplane/
lrwxrwxrwx 0 root 10 lip 15:42 asus::kbd_backlight -> ../../devices/pci0000:00/0000:00:08.1/0000:05:00.3/usb1/1-3/1-3:1.0/0003:0B05:1866.0002/leds/asus::kbd_backlight/
lrwxrwxrwx 0 root 10 lip 15:42 input17::capslock -> ../../devices/pci0000:00/0000:00:08.1/0000:05:00.3/usb1/1-4/1-4:1.0/0003:0B05:18C6.0005/input/input17/input17::capslock/
lrwxrwxrwx 0 root 10 lip 15:42 input17::compose -> ../../devices/pci0000:00/0000:00:08.1/0000:05:00.3/usb1/1-4/1-4:1.0/0003:0B05:18C6.0005/input/input17/input17::compose/
lrwxrwxrwx 0 root 10 lip 15:42 input17::kana -> ../../devices/pci0000:00/0000:00:08.1/0000:05:00.3/usb1/1-4/1-4:1.0/0003:0B05:18C6.0005/input/input17/input17::kana/
lrwxrwxrwx 0 root 10 lip 15:42 input17::numlock -> ../../devices/pci0000:00/0000:00:08.1/0000:05:00.3/usb1/1-4/1-4:1.0/0003:0B05:18C6.0005/input/input17/input17::numlock/
lrwxrwxrwx 0 root 10 lip 15:42 input17::scrolllock -> ../../devices/pci0000:00/0000:00:08.1/0000:05:00.3/usb1/1-4/1-4:1.0/0003:0B05:18C6.0005/input/input17/input17::scrolllock/
lrwxrwxrwx 0 root 10 lip 15:42 input23::capslock -> ../../devices/pci0000:00/0000:00:08.1/0000:05:00.4/usb3/3-2/3-2:1.2/0003:046D:C539.0004/0003:046D:4085.0006/input/input23/input23::capslock/
lrwxrwxrwx 0 root 10 lip 15:42 input23::compose -> ../../devices/pci0000:00/0000:00:08.1/0000:05:00.4/usb3/3-2/3-2:1.2/0003:046D:C539.0004/0003:046D:4085.0006/input/input23/input23::compose/
lrwxrwxrwx 0 root 10 lip 15:42 input23::kana -> ../../devices/pci0000:00/0000:00:08.1/0000:05:00.4/usb3/3-2/3-2:1.2/0003:046D:C539.0004/0003:046D:4085.0006/input/input23/input23::kana/
lrwxrwxrwx 0 root 10 lip 15:42 input23::numlock -> ../../devices/pci0000:00/0000:00:08.1/0000:05:00.4/usb3/3-2/3-2:1.2/0003:046D:C539.0004/0003:046D:4085.0006/input/input23/input23::numlock/
lrwxrwxrwx 0 root 10 lip 15:42 input23::scrolllock -> ../../devices/pci0000:00/0000:00:08.1/0000:05:00.4/usb3/3-2/3-2:1.2/0003:046D:C539.0004/0003:046D:4085.0006/input/input23/input23::scrolllock/
lrwxrwxrwx 0 root 10 lip 15:42 input36::capslock -> ../../devices/platform/AMDI0010:00/i2c-0/i2c-ASUE1403:00/0018:04F3:319A.0007/input/input36/input36::capslock/
lrwxrwxrwx 0 root 10 lip 15:42 input36::compose -> ../../devices/platform/AMDI0010:00/i2c-0/i2c-ASUE1403:00/0018:04F3:319A.0007/input/input36/input36::compose/
lrwxrwxrwx 0 root 10 lip 15:42 input36::kana -> ../../devices/platform/AMDI0010:00/i2c-0/i2c-ASUE1403:00/0018:04F3:319A.0007/input/input36/input36::kana/
lrwxrwxrwx 0 root 10 lip 15:42 input36::numlock -> ../../devices/platform/AMDI0010:00/i2c-0/i2c-ASUE1403:00/0018:04F3:319A.0007/input/input36/input36::numlock/
lrwxrwxrwx 0 root 10 lip 15:42 input36::scrolllock -> ../../devices/platform/AMDI0010:00/i2c-0/i2c-ASUE1403:00/0018:04F3:319A.0007/input/input36/input36::scrolllock/
lrwxrwxrwx 0 root 10 lip 15:42 phy0-led -> ../../devices/pci0000:00/0000:00:02.2/0000:03:00.0/leds/phy0-led/
```

**Comment by ldrahnik** [comment]
And exist even under devices?

**Comment by kamack38** [comment]
```
$ /sys/class/input/input17
drwxr-xr-x    - root 10 lip 15:42 capabilities/
lrwxrwxrwx    0 root 10 lip 16:24 device -> ../../../0003:0B05:18C6.0005/
drwxr-xr-x    - root 10 lip 16:24 event6/
drwxr-xr-x    - root 10 lip 15:42 id/
.rw-r--r-- 4,1k root 10 lip 16:24 inhibited
drwxr-xr-x    - root 10 lip 15:52 input17::capslock/
drwxr-xr-x    - root 10 lip 15:52 input17::compose/
drwxr-xr-x    - root 10 lip 15:52 input17::kana/
drwxr-xr-x    - root 10 lip 15:52 input17::numlock/
drwxr-xr-x    - root 10 lip 15:52 input17::scrolllock/
.r--r--r-- 4,1k root 10 lip 16:24 modalias
.r--r--r-- 4,1k root 10 lip 15:42 name
.r--r--r-- 4,1k root 10 lip 15:42 phys
drwxr-xr-x    - root 10 lip 16:24 power/
.r--r--r-- 4,1k root 10 lip 15:42 properties
lrwxrwxrwx    0 root 10 lip 15:42 subsystem -> ../../../../../../../../../../class/input/
.rw-r--r-- 4,1k root 10 lip 15:42 uevent
.r--r--r-- 4,1k root 10 lip 16:24 uniq
```

**Comment by kamack38** [comment]
Name of this device is `ASUSTek Computer Inc. N-KEY Device Keyboard`

**Comment by kamack38** [comment]
And also I don't have `xinput` command available.

**Comment by kamack38** [comment]
> Check also capabilities for found `touchpad` with these lines entered on the bottom for example:
> 
> ```
> # touchpad capatibilities
> fd_t = open('/dev/input/event' + str(touchpad), 'rb')
> d_t = Device(fd_t)
> result = dev_k.capabilities(verbose=True)
> ```
> 
> I see the same:
> 
> ```
> ...
> ('EV_LED', 17):
> [('LED_NUML', 0), ('LED_CAPSL', 1), ('LED_SCROLLL', 2)]
> ```

When I print them I get.
```
INFO:Pad:D_t: <libevdev.device.Device object at 0x7fabe09ebd00>
INFO:Pad:Result: {('EV_SYN', 0): [('SYN_REPORT', 0), ('SYN_CONFIG', 1), ('SYN_MT_REPORT', 2), ('SYN_DROPPED', 3), ('?', 4), ('?', 20)], ('EV_KEY', 1): [('KEY_ESC', 1), ('KEY_ENTER', 28), ('KEY_KPMINUS', 74), ('KEY_KPPLUS', 78), ('KEY_UP', 103), ('KEY_LEFT', 105), ('KEY_RIGHT', 106), ('KEY_DOWN', 108), (['KEY_MIN_INTERESTING', 'KEY_MUTE'], 113), ('KEY_VOLUMEDOWN', 114), ('KEY_VOLUMEUP', 115), ('KEY_POWER', 116), ('KEY_PAUSE', 119), ('KEY_STOP', 128), ('KEY_PROPS', 130), ('KEY_UNDO', 131), ('KEY_COPY', 133), ('KEY_OPEN', 134), ('KEY_PASTE', 135), ('KEY_FIND', 136), ('KEY_CUT', 137), ('KEY_HELP', 138), ('KEY_MENU', 139), ('KEY_CALC', 140), ('KEY_SLEEP', 142), ('KEY_WAKEUP', 143), ('KEY_FILE', 144), ('KEY_PROG1', 148), ('KEY_PROG2', 149), ('KEY_WWW', 150), (['KEY_COFFEE', 'KEY_SCREENLOCK'], 152), ('KEY_MAIL', 155), ('KEY_BOOKMARKS', 156), ('KEY_BACK', 158), ('KEY_FORWARD', 159), ('KEY_EJECTCD', 161), ('KEY_NEXTSONG', 163), ('KEY_PLAYPAUSE', 164), ('KEY_PREVIOUSSONG', 165), ('KEY_STOPCD', 166), ('KEY_RECORD', 167), ('KEY_REWIND', 168), ('KEY_PHONE', 169), ('KEY_CONFIG', 171), ('KEY_HOMEPAGE', 172), ('KEY_REFRESH', 173), ('KEY_EXIT', 174), ('KEY_SCROLLUP', 177), ('KEY_SCROLLDOWN', 178), ('KEY_NEW', 181), ('KEY_F21', 191), ('KEY_PROG3', 202), ('KEY_PROG4', 203), ('KEY_CLOSE', 206), ('KEY_PLAY', 207), ('KEY_FASTFORWARD', 208), ('KEY_BASSBOOST', 209), ('KEY_PRINT', 210), ('KEY_CAMERA', 212), ('KEY_CHAT', 216), ('KEY_SEARCH', 217), ('KEY_FINANCE', 219), ('KEY_BRIGHTNESSDOWN', 224), ('KEY_BRIGHTNESSUP', 225), ('KEY_KBDILLUMTOGGLE', 228), ('KEY_KBDILLUMDOWN', 229), ('KEY_KBDILLUMUP', 230), ('KEY_SAVE', 234), ('KEY_DOCUMENTS', 235), ('KEY_UNKNOWN', 240), ('KEY_VIDEO_NEXT', 241), (['KEY_BRIGHTNESS_AUTO', 'KEY_BRIGHTNESS_ZERO'], 244), ('KEY_DISPLAY_OFF', 245), ('KEY_RFKILL', 247), ('KEY_MICMUTE', 248), (['BTN_0', 'BTN_MISC'], 256), ('KEY_SELECT', 353), ('KEY_GOTO', 354), ('KEY_INFO', 358), ('KEY_PROGRAM', 362), ('KEY_PVR', 366), ('KEY_SUBTITLE', 370), (['KEY_FULL_SCREEN', 'KEY_ZOOM'], 372), ('KEY_KEYBOARD', 374), (['KEY_ASPECT_RATIO', 'KEY_SCREEN'], 375), ('KEY_PC', 376), ('KEY_TV', 377), ('KEY_TV2', 378), ('KEY_VCR', 379), ('KEY_VCR2', 380), ('KEY_SAT', 381), ('KEY_CD', 383), ('KEY_TAPE', 384), ('KEY_TUNER', 386), ('KEY_PLAYER', 387), ('KEY_DVD', 389), ('KEY_AUDIO', 392), ('KEY_VIDEO', 393), ('KEY_MEMO', 396), ('KEY_CALENDAR', 397), ('KEY_RED', 398), ('KEY_GREEN', 399), ('KEY_YELLOW', 400), ('KEY_BLUE', 401), ('KEY_CHANNELUP', 402), ('KEY_CHANNELDOWN', 403), ('KEY_LAST', 405), ('KEY_NEXT', 407), ('KEY_RESTART', 408), ('KEY_SLOW', 409), ('KEY_SHUFFLE', 410), ('KEY_PREVIOUS', 412), ('KEY_VIDEOPHONE', 416), ('KEY_GAMES', 417), ('KEY_ZOOMIN', 418), ('KEY_ZOOMOUT', 419), ('KEY_ZOOMRESET', 420), ('KEY_WORDPROCESSOR', 421), ('KEY_EDITOR', 422), ('KEY_SPREADSHEET', 423), ('KEY_GRAPHICSEDITOR', 424), ('KEY_PRESENTATION', 425), ('KEY_DATABASE', 426), ('KEY_NEWS', 427), ('KEY_VOICEMAIL', 428), ('KEY_ADDRESSBOOK', 429), ('KEY_MESSENGER', 430), (['KEY_BRIGHTNESS_TOGGLE', 'KEY_DISPLAYTOGGLE'], 431), ('KEY_SPELLCHECK', 432), ('KEY_LOGOFF', 433), ('KEY_MEDIA_REPEAT', 439), ('KEY_IMAGES', 442), ('KEY_BUTTONCONFIG', 576), ('KEY_TASKMANAGER', 577), ('KEY_JOURNAL', 578), ('KEY_CONTROLPANEL', 579), ('KEY_APPSELECT', 580), ('KEY_SCREENSAVER', 581), ('KEY_VOICECOMMAND', 582), ('KEY_ASSISTANT', 583), ('KEY_EMOJI_PICKER', 585), ('?', 586), ('KEY_BRIGHTNESS_MIN', 592), ('KEY_BRIGHTNESS_MAX', 593)], ('EV_REL', 2): [('REL_HWHEEL', 6), ('REL_HWHEEL_HI_RES', 12)], ('EV_ABS', 3): [(('ABS_VOLUME', 32), AbsInfo(value=0, min=0, max=572, fuzz=0, flat=0, resolution=0)), (('ABS_MISC', 40), AbsInfo(value=0, min=0, max=255, fuzz=0, flat=0, resolution=0))], ('EV_MSC', 4): [('MSC_SCAN', 4)]}
```

**Comment by kamack38** [comment]
```
$ /sys/class/input/event5
.r--r--r-- 4,1k root 10 lip 16:36 dev
lrwxrwxrwx    0 root 10 lip 16:36 device -> ../../input15/
drwxr-xr-x    - root 10 lip 16:36 power/
lrwxrwxrwx    0 root 10 lip 15:42 subsystem -> ../../../../../../../../../../../class/input/
.rw-r--r-- 4,1k root 10 lip 15:42 uevent
```

**Comment by kamack38** [comment]
So I think the issue may be that it wants to use the wrong device?
The `event5` name is `Asus Keyboard`
And the `input17` name is `ASUSTek Computer Inc. N-KEY Device Keyboard`

**Comment by kamack38** [comment]
So once again
```
$ /sys/class/input/input17
drwxr-xr-x    - root 10 lip 16:24 capabilities/
lrwxrwxrwx    0 root 10 lip 16:24 device -> ../../../0003:0B05:18C6.0005/
drwxr-xr-x    - root 10 lip 16:24 event6/
drwxr-xr-x    - root 10 lip 16:24 id/
.rw-r--r-- 4,1k root 10 lip 16:24 inhibited
drwxr-xr-x    - root 10 lip 15:52 input17::capslock/
drwxr-xr-x    - root 10 lip 15:52 input17::compose/
drwxr-xr-x    - root 10 lip 15:52 input17::kana/
drwxr-xr-x    - root 10 lip 15:52 input17::numlock/
drwxr-xr-x    - root 10 lip 15:52 input17::scrolllock/
.r--r--r-- 4,1k root 10 lip 16:24 modalias
.r--r--r-- 4,1k root 10 lip 16:24 name
.r--r--r-- 4,1k root 10 lip 16:24 phys
drwxr-xr-x    - root 10 lip 16:24 power/
.r--r--r-- 4,1k root 10 lip 16:24 properties
lrwxrwxrwx    0 root 10 lip 15:42 subsystem -> ../../../../../../../../../../class/input/
.rw-r--r-- 4,1k root 10 lip 16:24 uevent
.r--r--r-- 4,1k root 10 lip 16:24 uniq
```
```
$ /sys/class/input/input15
drwxr-xr-x    - root 10 lip 16:38 capabilities/
lrwxrwxrwx    0 root 10 lip 16:24 device -> ../../../0003:0B05:1866.0002/
drwxr-xr-x    - root 10 lip 16:24 event5/
drwxr-xr-x    - root 10 lip 16:38 id/
.rw-r--r-- 4,1k root 10 lip 16:38 inhibited
.r--r--r-- 4,1k root 10 lip 16:38 modalias
.r--r--r-- 4,1k root 10 lip 16:38 name
.r--r--r-- 4,1k root 10 lip 16:38 phys
drwxr-xr-x    - root 10 lip 16:38 power/
.r--r--r-- 4,1k root 10 lip 16:38 properties
lrwxrwxrwx    0 root 10 lip 15:42 subsystem -> ../../../../../../../../../../class/input/
.rw-r--r-- 4,1k root 10 lip 16:38 uevent
.r--r--r-- 4,1k root 10 lip 16:38 uniq
```

**Comment by ldrahnik** [comment]
And when you run ```sudo libinput debug-events``` from which keyboard are sent events?

**Comment by kamack38** [comment]
I changed `Asus Keyboard` to `ASUSTek Computer Inc. N-KEY Device Keyboard` at line 113, and it seems to be working, but unfortunately it isn't synchronized with the numlock status.

**Comment by kamack38** [comment]
I get events from `event6` when using keyboard and from `event10` when using touchpad.
`event6` is `input17` and `event10` is `input35`.

**Comment by kamack38** [comment]
`input35` name is `ASUE1403:00 04F3:319A Touchpad`

**Comment by kamack38** [comment]
When I list event names I get
```
...
ASUSTek Computer Inc. N-KEY Device
Asus Keyboard
ASUSTek Computer Inc. N-KEY Device Keyboard
...
ASUE1403:00 04F3:319A Mouse
ASUE1403:00 04F3:319A Touchpad
ASUE1403:00 04F3:319A Keyboard
...
```

**Comment by kamack38** [comment]
After trying all *keyboard like* devices, it turns out that it works only with `ASUSTek Computer Inc. N-KEY Device Keyboard` and `ASUE1403:00 04F3:319A Keyboard` I can use `xdotool key Num_Lock` to disable the *NoT*, but it won't enable it. I have to manually enable the *NoT* by clicking the *top right icon*

**Comment by ldrahnik** [comment]
Ok, good (y)

Activate numpad when is system numlock set up to 1 is in my opinion unwanted. When you want to manipulate with numpad you want enable it by yourself. When is external keyboard connected you use external keyboard and you do not even touch laptop. Please 1 example when it would be useful, an option parameter could be added. Maybe I miss something.

**Comment by kamack38** [comment]
Ok, I totally understand you, but the behavior on Windows is different. When you activate numlock on other keyboard, the *NoT* activates.

**Comment by kamack38** [comment]
You can choose what behavior you prefer, because it doesn't make any difference to me.

**Comment by ldrahnik** [comment]
So detection line as I pushed now works for you?

 `("Name=\"ASUE" in line and "Keyboard" in line)`

**Comment by ldrahnik** [comment]
And has been removed detection for `Asus Keyboard` as it does not contain numlock, looks like that was added in previously repo on any user demand without taking into account the inputs.

**Comment by kamack38** [comment]
Yes, it works perfectly! I also would like to ask you to not force push commits, because (at least for me) it defeats the whole purpose of Git.

**Review by kamack38 — APPROVED** [review]
LGTM

**Comment by ldrahnik** [comment]
You commited something to this branch? I will anyway squash these commits before merge. To master branch i will not force push anymore.

**Comment by kamack38** [comment]
No I didn't, but I had troubles pulling changes.

**Comment by ldrahnik** [comment]
Yeah, that makes me angry too. Sorry. Works like charm finally. Missing catch except code etc I will add later if needed.

And as mentioned before and for my future, deadlock IMHO would happen in this implementation local numlock state and global numlock state which can be changed from both sides makes perfect endless cycle. So for official driver implementation would have to be removed local state and only one resource would be system numlock.

**Pull request merged**
